# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :distribute do
    gradle(task: "clean")
    gradle(
      task: "assemble",
      flavor: "Prod",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "fastlane/keystore.jks",
        "android.injected.signing.store.password" => ENV["key_store_pass"],
        "android.injected.signing.key.alias" => ENV["alias_key"],
        "android.injected.signing.key.password" => ENV["alias_key_pass"],
      }
    )
    
    firebase_app_distribution(
      app: ENV["firebase_app_id"],
      apk_path: "Memorati/app/build/outputs/release/apk/prod/release/app-prod-release.apk",
      release_notes: "https://github.com/mtwalli/Memorati/releases/tag/#{ENV["release_tag"]}",
      groups_file: "fastlane/groups.txt",
      service_credentials_file: "fastlane/service_credentials.json"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
