name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3.5.0

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0

      - name: Check spotless
        run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

      - name: Check lint
        run: ./gradlew lintDemoDebug

      - name: Build all build type and flavor permutations
        run: ./gradlew assemble

      - name: Run local tests
        run: ./gradlew testDemoDebug testProdDebug

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4.3.6
        with:
          name: APKs
          path: '**/build/outputs/apk/**/*.apk'

      - name: Upload lint reports (HTML)
        if: always()
        uses: actions/upload-artifact@v4.3.6
        with:
          name: lint-reports
          path: '**/build/reports/lint-results-*.html'

      - name: Upload test results (XML)
        if: always()
        uses: actions/upload-artifact@v4.3.6
        with:
          name: test-results
          path: '**/build/test-results/test*UnitTest/**.xml'
